version: "2.0"

services:
  pidgin:
    container_name: pidgin
    image: alexandreoda/pidgin
    restart: "no"
    privileged: false
    volumes:
      - "${HOME}:/home/pidgin"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/"